# Generated by Django 3.1.4 on 2021-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.TextField(help_text='Icono', max_length=2000)),
                ('titulo', models.CharField(help_text='Título', max_length=20)),
                ('descripcion', models.CharField(help_text='Descripción', max_length=200)),
            ],
        ),
    ]
