# Generated by Django 3.1.4 on 2021-01-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210108_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.ImageField(upload_to=''),
        ),
    ]
