# Generated by Django 3.1.4 on 2021-01-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210108_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.FileField(max_length=20000, upload_to='./static/main/img/'),
        ),
    ]
