# Generated by Django 3.1.4 on 2021-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.TextField(max_length=20000),
        ),
    ]
